### ISSUE TITLE
java.lang.NoClassDefFoundError: io/confluent/kafka/serializers/subject/strategy/SubjectNameStrategy 	

### ISSUE THREAD

**Issue by huoarter** [cricket007/schema-registry-transfer-smt#11]
what errror is this ?
```
docker images: confluentinc/cp-kafka:5.1.2
connect-standalone --version
2.1.1-cp1 (Commit:9aa84c2aaa91e392)
```

```
[2019-04-08 02:37:22,627] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:119)
java.lang.NoClassDefFoundError: io/confluent/kafka/serializers/subject/strategy/SubjectNameStrategy
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:709)
	at org.apache.kafka.connect.runtime.ConnectorConfig.enrich(ConnectorConfig.java:301)
	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:271)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:188)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:113)
Caused by: java.lang.ClassNotFoundException: io.confluent.kafka.serializers.subject.strategy.SubjectNameStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by cricket007** [comment]
That class is what is responsible for handling the `-key` and `-value` renaming of the topic for the registry. 

I believe it was added in Confluent Platform 4.x

**Comment by cricket007** [comment]
And are you using the shaded JAR file? If so, then I'm not sure why you'd get that stacktrace, because I rename the Confluent packages as part of the build. 

Plus, if you're using `confluentinc/cp-kafka` Docker image, then that container doesn't load the `CONNECT_PLUGIN_PATH` variable. Maybe try `confluentinc/cp-kafka-connect` instead.

**Comment by huoarter** [comment]
Thx for your help ,When I try to use confluentinc/cp-kafka-connect, a new error appears.
```
[2019-04-08 03:25:30,790] ERROR WorkerSourceTask{id=kafka-connect-kafka-source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:50)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:292)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
[2019-04-08 03:25:30,791] ERROR WorkerSourceTask{id=kafka-connect-kafka-source-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
[2019-04-08 03:25:30,789] INFO WorkerSourceTask{id=kafka-connect-kafka-source-1} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:414)
[2019-04-08 03:25:30,791] INFO KafkaSourceTask@3c00d2ec: stop() called. Waking up consumer and shutting down (com.comcast.kafka.connect.kafka.KafkaSourceTask:215)
[2019-04-08 03:25:30,791] ERROR WorkerSourceTask{id=kafka-connect-kafka-source-1} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:50)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:292)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
[2019-04-08 03:25:30,792] INFO KafkaSourceTask@3c00d2ec: Shutting down consumer. (com.comcast.kafka.connect.kafka.KafkaSourceTask:226)
[2019-04-08 03:25:30,792] ERROR WorkerSourceTask{id=kafka-connect-kafka-source-1} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
```

**Comment by cricket007** [comment]
> `SerializationException: Unknown magic byte!` 

You'd see this error if even a single message in the topic is not Avro. Typically, people don't pass Avro keys, so I would suggest setting `transforms.AvroSchemaTransfer.transfer.message.keys=false`

**Comment by huoarter** [comment]
So, when  two type message ( Avro and not Avro) be mirrored  , two connector  config shoud be configured respectively？

**Comment by cricket007** [comment]
Correct. Similar to how Kafka producers and consumers are configured, you would have `key.serializer` and `value.serializer` configurations.

**Comment by huoarter** [comment]
I see. Thanks again.  You are very  kind , nice and handsome .

**Comment by cricket007** [comment]
I assume that fixed your issue? I'm going to go ahead and close this since we at least solved the first problem
