### ISSUE TITLE
Nullpointer exception when schema present but record value equals null

### ISSUE THREAD

**Issue by twiechert** [cricket007/schema-registry-transfer-smt#6]
In that case we experience:
`
at java.nio.ByteBuffer.wrap(ByteBuffer.java:396)
	at cricket.jmoore.kafka.connect.transforms.SchemaRegistryTransfer.apply(SchemaRegistryTransfer.java:128)
	at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:38)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:218)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

This will happen for example in combination with the comcast mirror tool, which in any case will set schema information even when the record is null.

**Comment by cricket007** [comment]
Hopefully this is resolved by #8
